# Camera
BOARD_CAMERA_SENSORS := ov8865_cm9462 ov2680
TARGET_USE_VENDOR_CAMERA_EXT := true
USE_DEVICE_SPECIFIC_CAMERA := true
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
TARGET_NEEDS_PLATFORM_TEXT_RELOCATIONS := true
BOARD_GLOBAL_CFLAGS += -DCONFIG_MLTE5_CAMERA -DCAMERA_VENDOR_L_COMPAT
